edtr-io/edtr-io

packages/core/__tests__/plugin-state.ts
packages/core/__tests__/store/index.ts
packages/core/package.json
packages/core/src/document/editor.tsx
packages/core/src/editor-context.tsx
packages/core/src/editor.tsx
packages/core/src/index.tsx
packages/core/src/plugin-state.ts
packages/core/src/store/reducer.ts
packages/demo/__stories__/index.tsx
packages/demo/__stories__/textPlugin.tsx
packages/plugin-text/src/factory/editor.tsx
yarn.lock

Follow up to #22: Debounce actions for undo/redo.
Actions can specify if they can be debounced or not. I added debounce to the Change Actions but not Insert or Remove.
Actions that don't have debounce set are commited as array of length 1, debounced append to last debounced actions if timeout isn't expired yet.

feature: debounce undo/redo

---

packages/core/__tests__/store/index.ts
packages/core/src/document/editor.tsx
packages/core/src/editor-context.tsx
packages/core/src/editor.tsx
packages/core/src/index.tsx
packages/core/src/store/reducer.ts
packages/demo/__stories__/index.tsx
packages/demo/__stories__/textPlugin.tsx
scripts/changelog.ts

- Added `PersistAction` to reducer.
- Added `changed` callback to Editor. The callback is called on every Action passing a boolean if the content changed since the last `PersistAction` was dispatched (or initial state).

Feat: Add changed callback to editor props

---

CHANGELOG.md
packages/core/src/editor.tsx
packages/core/src/store/reducer.ts
scripts/changelog.ts

 fix: only trigger changed callback when pending changes are different 

---

packages/core/__tests__/store/index.ts
packages/core/src/store/reducer.ts

Children didn't serialize the document. Fixed by passing a correct SerializeHelper
(builds up on #35 because I needed `serializePlugin` which I added there)

Fix: serialize of nested children

---

packages/plugin-rows/src/editor.tsx

Currently the rows menu opens fixed, which is nice in the default state: 
However, once you scroll it actually appears lower the further you scroll (leading to it being outside of the viewport really fast):
Moreover, if you open the menu at the bottom of the screen you can't actually see it anymore because it does not extend the screen to scroll.
Making it position:absolute resolves both of these issues. 
(Note, maybe you had deeper thoughts on making it position:fixed. If so, feel free to take over this PR and fix it another way :) )

Change rows menu appearance from fixed to absolute

---

CHANGELOG.md
packages/core/src/document/editor.tsx
packages/core/src/plugin.ts
packages/plugin-rows/src/editor.tsx
packages/plugin-text/src/factory/editor.tsx
scripts/changelog.ts

**core**. Added `name` prop to plugins
Used for:
- correct plugin name in slate inserts
- exclude rows plugin from add menu in rows plugin

fix: use correct plugin name in slate inserts

---

CHANGELOG.md
scripts/changelog.ts

I re-released 0.5.0, because last time npm release failed. Some additional commits are therefore included in 0.5.0 already.

changelog: correct changes on v0.5.0

---

packages/plugin-text/src/plugins/katex/editor.tsx
packages/plugin-text/src/plugins/markdown.ts

fix: markdown recognizes a ordered list only at the beginning of the line
fix: markdown does not overwrite the behavior of enter and backspace
fix: Block formulas are not allowed within a list. Inline option is not displayed.

some bug fixes for md-shortcuts and lists

---

CHANGELOG.md
packages/plugin-text/src/controls/index.tsx
scripts/changelog.ts

Auf touch Geräten wird das text selection menu unterhalb des Textes angezeigt, um zu verhindern, dass sich diese mit dem nativen Textauswahlmenü überlagert. Das timeout menu am unteren Rand des Bildschirms wird stattdessen am oberen Rand gerendert, damit es nicht durch die Tastatur überlagert wird.
Es ist nicht möglich im Browser das Text-Selection Menu zu ändern oder zu erweitern.
Auch ist es nicht möglich im Browser einen Listener auf die Tastatur zu setzen.

touch fixes

---

.eslint-ci.config.js
.eslint-extended-ci.config.js
.eslintrc.js
babel.config.js
package.json
packages/core/__helpers__/index.ts
packages/core/package.json
packages/core/src/editor.tsx
packages/core/src/store/history/reducer.ts
packages/core/src/store/store.ts
packages/demo/package.json
packages/demo/src/container/plain.tsx
packages/demo/src/container/serlo-with-preview.tsx
packages/demo/src/container/serlo.tsx
packages/renderer/package.json
packages/renderer/src/index.tsx
packages/store-devtools/.npmignore
packages/store-devtools/package.json
packages/store-devtools/src/index.ts
packages/store-devtools/src/tsconfig.json
packages/store-devtools/tsconfig.prod.json
tsconfig.json
yarn.lock

- **core**. `createStore` has a new required option `createStoreEnhancer`. Our high-level API (e.g. `<Editor />`, `<EditorProvider />` and `<Renderer />`) handle that change in a non-breaking way, though.
- **core**. Expose `getUndoStack` and `getRedoStack` selectors
- **core**. Store no longer applies enhancers used for testing or development purposes. Instead,  `<Editor />`, `<EditorProvider />` and `<Renderer />` provide a new optional prop `createStoreEnhancer` that allows to extend the store enhancer used. Our previous enhancer for development is published as a new package `@edtr-io/store-devtools` (e.g. used in our demo).

Sprint 2019-08-24

---

packages/plugin-text/src/plugins/katex/editor.tsx
packages/plugin-text/src/plugins/katex/index.tsx
packages/ui-editor/src/components/overlay-textarea.tsx
packages/ui-renderer/src/components/textarea.tsx

Bug:
1. Edit any math field
2. click outside of plugin
3. Edit is lost :(
Problem:
EditorComponent is remounted when plugin is changed, unfortunately this destroys all local state
Fix:
Each slate katex plugins gets a cache (which persists remounts) that holds all uncomitted changes

fix loosing edits when clicking outside of plugin

---

docs/Theming.md
packages/ui/src/editor-theme.ts

- **plugin-text**. Fix colors of editor ui in edge and safari
fixes #197

fix color of editor-ui for edge and safari

---

packages/plugin-text/src/factory/editor.tsx

- **plugin-text**. Split on enter now works also when theres a list in the same block.
I reverted parts of #135 because the split on paste is broken atm., especially when you replace a whole block. We need to implement a smarter solution for this. One issue I ran into while trying to fix it, is that all blocks below the insert will be split, and we don't want that at normal line-breaks...

fix: don't split on paste and split correctly on enter

---

packages/plugin-input-exercise/src/index.ts
packages/renderer-ssr/__tests-ssr__/index.ts

- **plugin-input-exercise**. Use `migratable` in state for backwards compatibility with pre v0.11.2 state

fix: backwards compatibility with migratable

---

packages/plugin-text/src/controls/default.tsx

If you want to remove a heading, you click on the heading button to enter the subcontrols. You can remove it or change heading level.
This behaviour feels a bit more comfortable

heading always entering subcontrols

---

packages/abstract-plugin/src/index.ts
packages/core/src/document/editor.tsx
packages/plugin-anchor/src/editor.tsx
packages/plugin-geogebra/src/editor.tsx
packages/plugin-highlight/src/editor.tsx
packages/plugin-image/src/editor.tsx
packages/plugin-serlo-injection/src/editor.tsx
packages/plugin-spoiler/src/editor.tsx
packages/plugin-table/src/editor.tsx
packages/plugin-video/src/editor.tsx
packages/ui-editor/src/components/editor-input.tsx
packages/ui-editor/src/components/overlay-input.tsx
packages/ui-renderer/src/components/textarea.tsx

(for now building up on #229 because of the injection changes)
- **plugin**. Additional prop for plugins `defaultFocusRef`: Ref to use for an input element. The element will receive focus, when the plugin is focused
- **all**. Fixed focus movement with arrow keys.

fix focus movement through plugins

---

packages/public/editor-ui/src/components/preview-overlay.tsx

- **editor-ui**. Position PreviewOverlay over content (for blur) using z-index

fix: z-index position overlay over content

---

jest.config.js
packages/plugins/highlight/package.json
packages/plugins/highlight/src/editor.tsx
packages/plugins/highlight/src/index.ts
packages/plugins/highlight/src/renderer.tsx
yarn.lock

Refactor the highlight plugin to reduce bundlesize: The react-syntax-highlighter is now used as `PrismAsyncLight`. You can override it by importing `createHighlightPlugin` instead and passing a render component which accepts the following props:
```
interface HighlightRendererProps {
code: string,
language: string,
lineNumbers: boolean
} 
```
TODO:
-  export highlightPlugin instead of `createHighlightPluginWithDefault`
- cleanup

refactor highlight plugin

---

packages/private/demo/__stories__/toolbar.tsx
packages/private/demo/package.json
packages/private/document-editor/src/index.ts
packages/public/core/package.json
packages/public/core/src/document/editor.tsx
packages/public/default-document-editor/src/index.tsx
packages/public/renderer-ssr/package.json

- **default-document-editor**. Show toolbar if `renderIntoToolbar` was called somewhere
- **default-document-editor**. Show default settings menu if `renderIntoSettings` was called somewhere

fix: show toolbar if renderIntoToolbar was called somewhere

---

package.json
packages/private/bundle-size/package.json
packages/private/demo/package.json
packages/public/editor-ui/package.json
packages/public/renderer-ssr/package.json
packages/public/renderer-ui/package.json
packages/public/ui/package.json
yarn.lock

Uses the [newly released styled-components v5](https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987). Since there is no breaking change between v4 and v5, we can safely allow both versions as `peerDependency` and let users decide if they want to use v5.

styled-components v5

---

api/store.api.md
packages/public/store/__tests__/history.ts
packages/public/store/src/history/reducer.ts
packages/public/store/src/types.ts

Currently it is not possible to determine whether there are actions which can be redo. At serlo.org there is the line (see https://github.com/serlo/serlo.org/blob/cff526b0fddfa91240ba56c6047cb6a62e450dc1/packages/private/edtr-io/src/plugins/types/common.tsx#L108-L110 ):
```ts
const redoable = pendingChanges < 0
```
However, when I understand the code at https://github.com/edtr-io/edtr-io/blob/master/packages/public/store/src/history/reducer.ts correctly, pendingChanges is the total number of made actions starting from the beginning due to the current state. Thus, this number can never be negative. To test whether there are undo / redo actions it would be easier to check, whether `undoStack` or `redoStack` are empty or not.
**Sidenote:** The Selector `hasPendingChanges()` should be the …

Add hasRedoActions() and hasUndoActions()

---

.eslintrc.js

I got the error "Parsing error: Cannot read file
'.../tsconfig.json'.eslint" when I edit in this repository with neovim +
coc. Adding the `tsconfigRootDir` solved this issue.
See also https://stackoverflow.com/a/64940811

Add tsconfigRootDir to .eslintrc.js

---

packages/private/demo/__stories__/math.tsx
packages/public/math/src/editor.tsx

The overlay should not hide previous text and thus the default position
of the overlay shall be "below". We got this feedback from the authors
at serlo.org.

math: Set position of overlay to "below"

---

packages/public/math/src/editor.tsx

After the feedback I got from @kathongi the overlay shall be shown above again.

Set overlay of math editor to above

---

packages/public/store/src/store.ts
packages/public/ui/src/icon.tsx
packages/public/ui/src/index.ts

Avoid using `default-import` package, it's needed in the ui package, so we include the source code directly (mostly bypassing type-checking for now)

load esm module from cjs
