edtr-io/edtr-io

- packages/core/__tests__/store/index.ts
- packages/core/src/document/editor.tsx
- packages/core/src/document/index.tsx
- packages/core/src/document/renderer.tsx
- packages/core/src/editor-context.tsx
- packages/core/src/editor.tsx
- packages/core/src/store/reducer.ts
- packages/demo/__stories__/index.tsx
- packages/ui/src/plugin-rows/clipboard.tsx
- scripts/changelog.ts
added `editable` prop to Editor for switching between edit and render mode
> feature: enable switch between edit and render mode

- CHANGELOG.md
- docs/Plugins.md
- docs/Theming.md
- lint-staged.config.js
- package.json
- packages/demo/.storybook/config.js
- packages/demo/.storybook/webpack.config.js
- packages/demo/package.json
- packages/plugin-anchor/package.json
- packages/plugin-blockquote/package.json
- packages/plugin-geogebra/package.json
- packages/plugin-highlight/package.json
- packages/plugin-image/package.json
- packages/plugin-rows/package.json
- packages/plugin-spoiler/package.json
- packages/plugin-text/package.json
- packages/ui/src/elements/onClickOutside.tsx
- scripts/changelog.ts
- yarn.lock
Updates deps, some minor config changes (prettier & storybook)
> Build demo

- CHANGELOG.md
- packages/demo/.storybook/webpack.config.js
- packages/demo/__stories__/plugin-video.tsx
- packages/demo/src/plugins.tsx
- packages/plugin-video/package.json
- packages/plugin-video/src/editor.tsx
- packages/plugin-video/src/index.ts
- packages/plugin-video/src/renderer.tsx
- packages/plugin-video/src/tsconfig.json
- packages/ui/src/icon.ts
- scripts/changelog.ts
- tsconfig.json
> feat: add video plugin

- CHANGELOG.md
- packages/plugin-image/src/editor.tsx
- packages/plugin-image/src/index.ts
- packages/plugin-image/src/upload.tsx
- packages/plugin-rows/src/editor.tsx
- packages/ui/src/elements/button.tsx
- packages/ui/src/elements/checkbox.tsx
- packages/ui/src/elements/index.ts
- packages/ui/src/elements/input.tsx
- packages/ui/src/elements/settings-overlay.tsx
- packages/ui/src/elements/textarea.tsx
- scripts/changelog.ts
- Added Checkbox, Button and Textarea components for overlay
- Added onPaste handler for image plugin accepting jpg, png, bmp, gif, svg
> image plugin styling and onPaste

- packages/ui/src/elements/settings-overlay.tsx
Position inline overlay absolute instead of fixed
> fix inline overlay positioning

- CHANGELOG.md
- babel.config.js
- packages/demo/__stories__/plugin-equations.tsx
- packages/demo/src/plugins.tsx
- packages/plugin-equations/package.json
- packages/plugin-equations/src/editor.tsx
- packages/plugin-equations/src/index.ts
- packages/plugin-equations/src/renderer.tsx
- packages/plugin-equations/src/tsconfig.json
- scripts/changelog.ts
- tsconfig.json
- yarn.lock
> feature equations for edtr-io

- CHANGELOG.md
- packages/demo/__stories__/plugin-image.tsx
- packages/plugin-image/src/editor.tsx
- packages/plugin-image/src/index.ts
- packages/plugin-image/src/renderer.tsx
- scripts/changelog.ts
Maxwidth for images
Image-plugin has new required 'maxwidth' - state property
hide config-overlay in render mode
> Adding maxwidth property in overlay

- CHANGELOG.md
- babel.config.js
- packages/demo/__stories__/plugin-h5p.tsx
- packages/demo/src/plugins.tsx
- packages/plugin-h5p/package.json
- packages/plugin-h5p/src/editor.tsx
- packages/plugin-h5p/src/index.ts
- packages/plugin-h5p/src/renderer.tsx
- packages/plugin-h5p/src/tsconfig.json
- scripts/changelog.ts
- tsconfig.json
Error image in Background, link does not load
> h5p plugin adapted for edtr-io; tested link does not load

- packages/plugin-anchor/package.json
- packages/plugin-blockquote/package.json
- packages/plugin-equations/package.json
- packages/plugin-geogebra/package.json
- packages/plugin-h5p/package.json
- packages/plugin-highlight/package.json
- packages/plugin-hint/package.json
- packages/plugin-image/package.json
- packages/plugin-input-exercise/package.json
- packages/plugin-rows/package.json
- packages/plugin-sc-mc-exercise/package.json
- packages/plugin-solution/package.json
- packages/plugin-spoiler/package.json
- packages/plugin-text/package.json
- packages/plugin-video/package.json
> Release 0.5

- CHANGELOG.md
- packages/plugin-text/src/factory/editor.tsx
- packages/plugin-text/src/factory/index.tsx
- packages/plugin-text/src/factory/types.ts
- packages/plugin-text/src/plugins/index.ts
- packages/plugin-text/src/plugins/plugin-suggestions.tsx
- packages/plugin-text/src/plugins/suggestions.tsx
- scripts/changelog.ts
- **plugin-text**. Poweruser-Feature: Add new plugins with /[plugintitle] in editmode
Only working in an empty textplugin.
Write "/" and a random letter to get suggestions.
Insert by pressing enter or click on the dropdown-field.
closes #117
> Poweruserfeature: add new plugins with /[pluginname]

- packages/plugin-rows/src/editor/controls/settings.tsx
- packages/plugin-rows/src/editor/row.tsx
- packages/plugin-rows/src/renderer.tsx
- packages/plugin-rows/src/row-container.tsx
> renderer of rows takes no extra space

- CHANGELOG.md
- packages/core/src/plugin-state/upload.ts
- scripts/changelog.ts
- **core**. Fix `StateType.upload`
> fix(core): don't use Promise.finally in upload

- packages/core/src/document/editor.tsx
- packages/core/src/store/documents/reducer.ts
- packages/store-devtools/package.json
- packages/store-devtools/src/index.ts
- yarn.lock
Removing two resource hogs:
- check for immutable state invariant middleware
- check for isEmpty on every redux-saga dispatch
Improves performance by about 8x :) (measured in dev mode)
> Improving performance

- packages/core/src/editor.tsx
- packages/core/src/index.tsx
- packages/core/src/preference-context.tsx
- packages/plugin-text/src/plugins/katex/editor.tsx
- packages/plugin-text/src/plugins/katex/math-component.tsx
> saving preference for visual math / no alert when latex error occures

- packages/plugin-text/src/plugins/katex/editor.tsx
- packages/plugin-text/src/plugins/katex/math-component.tsx
- packages/ui-editor/src/components/settings-overlay.tsx
polishing math input, more decent error messages, breakable block formulas
> improving math input

- packages/core/src/index.tsx
- packages/core/src/preference-context.tsx
- packages/plugin-rows/src/editor/index.tsx
- packages/plugin-rows/src/editor/row.tsx
- packages/plugin-text/src/factory/editor.tsx
- packages/plugin-text/src/plugins/katex/editor.tsx
- packages/plugin-text/src/plugins/katex/index.tsx
- yarn.lock
plugin-rows: using better selector and add useCallback to reduce render calls
plugin-text: slate-editor useMemo and cleaning up / simplify katex / default to visual
> Some optimizations

- packages/plugin-image/src/editor.tsx
- packages/plugin-image/src/index.ts
- packages/plugin-image/src/renderer.tsx
- packages/plugin-text/package.json
- yarn.lock
- **plugin-image**. Improved visibility of errors and upload status of images
> plugin-image: Improve visibility of errors and upload status of images

- CHANGELOG.md
- packages/plugin-input-exercise/src/index.ts
- packages/plugin-sc-mc-exercise/src/answers-renderer.tsx
- packages/plugin-sc-mc-exercise/src/helpers.ts
- packages/plugin-text/src/factory/editor.tsx
- packages/renderer-ssr/__tests-ssr__/index.ts
- packages/renderer-ssr/package.json
- scripts/changelog.ts
- yarn.lock
- **plugin-text**. Fixed server side rendering
- **plugin-sc-mc-exercise**. Fixed server side rendering
- **renderer-ssr**. Tests now test for correct results additionally to working server side rendering.
> Fix server side rendering

- packages/plugin-hint/src/editor.tsx
- packages/plugin-solution/src/editor.tsx
- packages/plugin-spoiler/src/editor.tsx
- packages/renderer-ssr/__tests-ssr__/index.ts
- packages/ui-renderer/src/components/expandable-box.tsx
- removed additional title from solution and hint 
- expandable box is now not collapsed by default
> fixes for hint, solution and spoiler

- packages/plugin-text/src/plugins/katex/editor.tsx
- packages/ui-renderer/src/components/textarea.tsx
This will autofocus textarea when using strg-m
> focus latex textarea on mount if it is empty

- packages/demo/__stories__/plugin-video.ts
- packages/plugin-video/src/editor.tsx
- packages/plugin-video/src/index.tsx
- packages/plugin-video/src/renderer.tsx
- packages/renderer-ssr/__tests-ssr__/index.ts
- state update: added alt-field to video plugin
-also show url-field in extended settings
> Video plugin improvements

- packages/plugins/text/src/plugins/colors.tsx
- packages/public/renderer-ssr/__tests-ssr__/index.ts
- Serverside rendering of color textplugin
> fix serverside rendering of the color textplugin

- .eslintrc.js
- .github/workflows/storybook.yml
- .github/workflows/workflow.yml
- package.json
- packages/private/demo/package.json
- packages/private/demo/scripts/deploy.ts
- yarn.lock
Storybook published via CI: https://storybook.edtr.io/feature%2Fpreview-deployment/ (mind the URL-encoded branch name and trailing slash)
> Preview Deployments

- packages/public/plugin/src/child.tsx
- packages/public/store/package.json
- packages/public/store/src/documents/reducer.ts
> fix rerender issues with serializedDocument selector

- packages/private/document-editor/src/index.ts
- packages/private/plugin/src/index.ts
- packages/public/core/src/document/editor.tsx
- packages/public/core/src/document/renderer.tsx
- packages/public/default-document-editor/src/index.tsx
- packages/public/default-plugin-toolbar/src/plugin-toolbar-button.tsx
> feature: add renderIntoToolbar to plugin props

- packages/plugins/rows/src/editor/render.tsx
> fix drag and drop on chrome

- packages/plugins/text/src/factory/editor.tsx
> hotfix: serialize slate state before insert

- .eslintrc.js
- package.json
- yarn.lock
Follow up PR when #320 got merged (This PR introduces the testing of react components so I based this PR on the other branch, since this is a new issue there might a discussion I opened a new PR): This PR installs the following eslint plugins:
* https://github.com/testing-library/eslint-plugin-testing-library
* https://github.com/testing-library/eslint-plugin-jest-dom
The recommended rules are added. Also there are the following rules:
* https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/no-debug.md
* https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/no-dom-import.md with setting to `react` as default library ( I guess we will only test react components )
* …
> Add recommended plugins to eslint for react testing

- packages/plugins/text/src/factory/editor.tsx
> fix: prevent backspace key triggering browser hotkeys

- api/editor-ui.api.md
- api/plugin-input-exercise.api.md
- api/plugin-sc-mc-exercise.api.md
- packages/plugins/highlight/src/editor.tsx
- packages/plugins/input-exercise/src/editor.tsx
- packages/plugins/input-exercise/src/index.ts
- packages/plugins/multimedia-explanation/src/editor.tsx
- packages/plugins/sc-mc-exercise/src/editor.tsx
- packages/plugins/sc-mc-exercise/src/index.ts
- packages/public/default-plugin-toolbar/src/overlay-select.tsx
- packages/public/editor-ui/src/interactive-answer-component.tsx
See https://github.com/serlo/serlo.org/issues/348
Changes:
* Option for type shall always be visible
* Add explanations "answer" and "feedback"
> Add improvements to sc/mc and input exercises

- api/plugin-rows.api.md
- api/plugin-text.api.md
- packages/plugins/rows/src/editor/index.tsx
- packages/plugins/rows/src/index.tsx
- packages/plugins/rows/src/registry-context.ts
- packages/plugins/text/package.json
- packages/plugins/text/src/config.tsx
- packages/plugins/text/src/index.tsx
- yarn.lock
> plugin-rows: expose registry via context

- packages/plugins/image/src/config.ts
- packages/plugins/image/src/index.ts
> image-plugin: small string change

- packages/plugins/image/src/index.ts
> image-captions: no colors

- packages/plugins/image/src/editor.tsx
- packages/plugins/image/src/renderer.tsx
Sorry for the incremental changes. 
It's often after the features are on staging or in production that the opinions form in the users…
I guess it's … agile? 😅
> image: show description only in settings
